expose_php = Off
memory_limit = 512M
upload_max_filesize = 25M
post_max_size = 26M
max_execution_time = 60
opcache.enable = 1
opcache.validate_timestamps = ${PHP_OPCACHE_VALIDATE_TIMESTAMPS}
session.cookie_httponly = 1
session.cookie_secure = 1
